# Generated by Django 5.2.5 on 2025-12-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_contactus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATSHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_role", models.CharField(max_length=64)),
                ("file", models.FileField(upload_to="ats/resumes/")),
                ("ats_score", models.IntegerField()),
                ("matched_keywords", models.JSONField(default=list)),
                ("missing_keywords", models.JSONField(default=list)),
                ("issues", models.JSONField(default=list)),
                ("ai_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
