# Generated by Django 5.2.5 on 2025-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_dob_student_github_student_interested_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DateField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
