# Generated by Django 5.2.5 on 2025-09-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='title',
        ),
        migrations.AddField(
            model_name='internship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='role',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
