# Generated by Django 5.2.5 on 2025-09-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_internship_duration_remove_internship_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.student'),
        ),
    ]
